#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := clock

CFLAGS = -DSNTP_UPDATE_DELAY=180000

include $(IDF_PATH)/make/project.mk

