#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := clock

CFLAGS = -Wno-deprecated-declarations
CPPFLAGS = -Wno-deprecated-declarations

include $(IDF_PATH)/make/project.mk

